var urls = ['https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/af-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ax-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/al-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ag-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/aq-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/an-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ao-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/av-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ac-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ar-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/am-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/aa-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/at-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/as-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/au-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/aj-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/bf-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ba-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/bg-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/bb-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/bo-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/be-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/bh-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/bn-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/bd-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/bt-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/bl-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/bk-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/bc-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/bv-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/br-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/io-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/vi-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/bx-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/bu-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/uv-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/bm-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/by-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/cv-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/cb-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/cm-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ca-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/cj-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ct-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/cd-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ci-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ch-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/kt-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ip-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ck-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/co-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/cn-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/cg-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/cf-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/cw-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/cr-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/cs-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/iv-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/hr-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/cu-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/cc-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/cy-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ez-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/da-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/dx-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/dj-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/do-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/dr-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ec-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/eg-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/es-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ek-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/er-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/en-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/et-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/fk-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/fo-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/fj-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/fi-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/fr-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/fp-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/fs-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/gb-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ga-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/gg-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/gm-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/gh-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/gi-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/gr-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/gl-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/gj-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/gq-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/gt-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/gk-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/gv-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/pu-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/gy-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ha-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/hm-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/vt-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ho-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/hk-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/hu-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ic-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/in-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/id-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ir-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/iz-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ei-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/im-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/is-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/it-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/jm-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/jn-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ja-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/je-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/jo-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/kz-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ke-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/kr-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/kn-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ks-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/kv-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ku-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/kg-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/la-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/lg-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/le-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/lt-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/li-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ly-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ls-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/lh-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/lu-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/mc-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/mk-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ma-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/mi-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/my-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/mv-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ml-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/mt-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/rm-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/mr-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/mp-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/mx-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/fm-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/md-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/mn-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/mg-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/mj-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/mh-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/mo-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/mz-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/wa-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/nr-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/np-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/nl-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/nc-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/nz-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/nu-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ng-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ni-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ne-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/nf-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/cq-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/no-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/mu-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/pk-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ps-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/pm-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/pp-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/pa-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/pe-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/rp-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/pc-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/pl-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/po-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/rq-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/qa-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ro-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/rs-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/rw-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/tb-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/sh-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/sc-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/st-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/rn-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/sb-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/vc-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ws-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/sm-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/tp-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/sa-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/sg-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ri-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/se-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/sl-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/sn-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/sk-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/lo-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/si-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/bp-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/so-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/sf-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/sx-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/od-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/sp-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ce-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/su-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ns-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/sv-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/wz-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/sw-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/sz-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/sy-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/tw-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ti-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/tz-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/th-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/tt-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/to-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/tl-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/tn-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/td-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ts-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/tu-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/tx-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/tk-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/tv-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ug-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/up-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ae-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/uk-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/us-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/um-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/uy-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/uz-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/nh-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ve-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/vm-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/vq-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/wq-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/wf-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ym-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/za-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/zi-lgflag.gif',
'https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ee-lgflag.gif']
var countryNames = [
'Afghanistan',
'Akrotiri',
'Albania',
'Algeria',
'American Samoa',
'Andorra',
'Angola',
'Anguilla',
'Antigua and Barbuda',
'Argentina',
'Armenia',
'Aruba',
'Ashmore and Cartier Islands',
'Australia',
'Austria',
'Azerbaijan',
'Bahamas, The',
'Bahrain',
'Bangladesh',
'Barbados',
'Belarus',
'Belgium',
'Belize',
'Benin',
'Bermuda',
'Bhutan',
'Bolivia',
'Bosnia and Herzegovina',
'Botswana',
'Bouvet Island',
'Brazil',
'British Indian Ocean Territory',
'British Virgin Islands',
'Brunei',
'Bulgaria',
'Burkina Faso',
'Burma',
'Burundi',
'Cabo Verde',
'Cambodia',
'Cameroon',
'Canada',
'Cayman Islands',
'Central African Republic',
'Chad',
'Chile',
'China',
'Christmas Island',
'Clipperton Island',
'Cocos (Keeling) Islands',
'Colombia',
'Comoros',
'Congo, Democratic Republic of the',
'Congo, Republic of the',
'Cook Islands',
'Coral Sea Islands',
'Costa Rica',
'Cote d\'Ivoire',
'Croatia',
'Cuba',
'Curacao',
'Cyprus',
'Czechia',
'Denmark',
'Dhekelia',
'Djibouti',
'Dominica',
'Dominican Republic',
'Ecuador',
'Egypt',
'El Salvador',
'Equatorial Guinea',
'Eritrea',
'Estonia',
'Ethiopia',
'Falkland Islands (Islas Malvinas)',
'Faroe Islands',
'Fiji',
'Finland',
'France',
'French Polynesia',
'French Southern and Antarctic Lands',
'Gabon',
'Gambia, The',
'Georgia',
'Germany',
'Ghana',
'Gibraltar',
'Greece',
'Greenland',
'Grenada',
'Guam',
'Guatemala',
'Guernsey',
'Guinea',
'Guinea-Bissau',
'Guyana',
'Haiti',
'Heard Island and McDonald Islands',
'Holy See (Vatican City)',
'Honduras',
'Hong Kong',
'Hungary',
'Iceland',
'India',
'Indonesia',
'Iran',
'Iraq',
'Ireland',
'Isle of Man',
'Israel',
'Italy',
'Jamaica',
'Jan Mayen',
'Japan',
'Jersey',
'Jordan',
'Kazakhstan',
'Kenya',
'Kiribati',
'Korea, North',
'Korea, South',
'Kosovo',
'Kuwait',
'Kyrgyzstan',
'Laos',
'Latvia',
'Lebanon',
'Lesotho',
'Liberia',
'Libya',
'Liechtenstein',
'Lithuania',
'Luxembourg',
'Macau',
'Macedonia',
'Madagascar',
'Malawi',
'Malaysia',
'Maldives',
'Mali',
'Malta',
'Marshall Islands',
'Mauritania',
'Mauritius',
'Mexico',
'Micronesia, Federated States of',
'Moldova',
'Monaco',
'Mongolia',
'Montenegro',
'Montserrat',
'Morocco',
'Mozambique',
'Namibia',
'Nauru',
'Nepal',
'Netherlands',
'New Caledonia',
'New Zealand',
'Nicaragua',
'Niger',
'Nigeria',
'Niue',
'Norfolk Island',
'Northern Mariana Islands',
'Norway',
'Oman',
'Pakistan',
'Palau',
'Panama',
'Papua New Guinea',
'Paraguay',
'Peru',
'Philippines',
'Pitcairn Islands',
'Poland',
'Portugal',
'Puerto Rico',
'Qatar',
'Romania',
'Russia',
'Rwanda',
'Saint Barthelemy',
'Saint Helena, Ascension, and Tristan da Cunha',
'Saint Kitts and Nevis',
'Saint Lucia',
'Saint Martin',
'Saint Pierre and Miquelon',
'Saint Vincent and the Grenadines',
'Samoa',
'San Marino',
'Sao Tome and Principe',
'Saudi Arabia',
'Senegal',
'Serbia',
'Seychelles',
'Sierra Leone',
'Singapore',
'Sint Maarten',
'Slovakia',
'Slovenia',
'Solomon Islands',
'Somalia',
'South Africa',
'South Georgia and South Sandwich Islands',
'South Sudan',
'Spain',
'Sri Lanka',
'Sudan',
'Suriname',
'Svalbard',
'Swaziland',
'Sweden',
'Switzerland',
'Syria',
'Taiwan',
'Tajikistan',
'Tanzania',
'Thailand',
'Timor-Leste',
'Togo',
'Tokelau',
'Tonga',
'Trinidad and Tobago',
'Tunisia',
'Turkey',
'Turkmenistan',
'Turks and Caicos Islands',
'Tuvalu',
'Uganda',
'Ukraine',
'United Arab Emirates',
'United Kingdom',
'United States',
'United States Pacific Island Wildlife Refuges',
'Uruguay',
'Uzbekistan',
'Vanuatu',
'Venezuela',
'Vietnam',
'Virgin Islands',
'Wake Island',
'Wallis and Futuna',
'Yemen',
'Zambia',
'Zimbabwe',
'European Union']


var correctButtonChoice = 0;
var points = 0;
function fotw(){
  var countryChoiceIndex = Math.floor(Math.random()*(countryNames.length));
  console.log(countryNames[countryChoiceIndex]);
  document.getElementById('fotwImage').src = urls[countryChoiceIndex];
  var buttons = document.getElementsByClassName('flagChoiceButton');
  correctButtonChoice = Math.floor(Math.random()*4)
  var countiesChosen = []
  for(i=0;i<4;i++){
    if(i == correctButtonChoice){
      document.getElementById(('flagChoiceButton'+(i+1)).toString()).innerHTML = countryNames[countryChoiceIndex];
    }else{
      document.getElementById(('flagChoiceButton'+(i+1)).toString()).innerHTML = countryNames[Math.floor(Math.random()*countryNames.length)]
    }
  }
}

function fotwButtonPress(calledId){
  console.log(Number(calledId))
  if(Number(calledId)-1 == correctButtonChoice){
    document.getElementById('answerIndicator').style.color = "#00cc00";
    document.getElementById('answerIndicator').innerHTML = "Correct!";
    points = points +2;
    document.getElementById('pointsIndicator').innerHTML = "points: "+points;
    fotw()
  }else{
    document.getElementById('answerIndicator').style.color = "#cc0000";
    document.getElementById('answerIndicator').innerHTML = "Inorrect, Try again.";
    points = points -1;
    document.getElementById('pointsIndicator').innerHTML = "points: "+points;
  }
}
